const langData = {
    vi: {
        nav_about: "Giới thiệu",
        nav_mission: "Sứ mệnh",
        nav_products: "Sản phẩm",
        nav_reasons: "Vì sao chọn SAFEALL",
        hero_title: "Chuẩn bị hôm nay –<br><span class=\"highlight\">An toàn ngày mai</span>",
        hero_desc: "Bảo vệ gia đình bạn trước mọi tình huống khẩn cấp với các bộ kit thiết yếu từ SAFEALL.",
        hero_cta: "Khám phá bộ kit",
        about_title: "Về SAFEALL",
        about_desc: "SAFEALL là thương hiệu cung cấp các bộ kit chuẩn bị khẩn cấp dành cho hộ gia đình tại Việt Nam, giúp mọi người sẵn sàng ứng phó với các tình huống như lũ lụt, cháy nổ và các thảm họa bất ngờ.",
        vision_title: "Tầm nhìn",
        vision_desc: "Xây dựng cộng đồng gia đình Việt Nam an toàn và chủ động trước các tình huống khẩn cấp.",
        mission_title: "Sứ mệnh",
        mission_desc: "Cung cấp các bộ kit chuẩn bị khẩn cấp dễ sử dụng, đáng tin cậy và phù hợp với nhu cầu của hộ gia đình.",
        goals_title: "Mục tiêu",
        goals_1: "Nâng cao nhận thức về chuẩn bị khẩn cấp cho hộ gia đình",
        goals_2: "Cung cấp các bộ kit an toàn và đáng tin cậy",
        goals_3: "Xây dựng cộng đồng chủ động trong việc phòng ngừa rủi ro",
        products_title: "Danh mục sản phẩm",
        products_subtitle: "Chọn bộ kit phù hợp với nhu cầu bảo vệ gia đình bạn.",
        prod_flood_title: "Bộ kit ứng phó lũ lụt",
        prod_flood_desc: "Được thiết kế chuyên biệt để bảo vệ gia đình trong các tình huống ngập lụt, bao gồm vật dụng chống nước và phao cứu sinh.",
        prod_fire_title: "Bộ kit ứng phó cháy nổ",
        prod_fire_desc: "Giúp gia đình bạn thoát hiểm an toàn khi xảy ra hỏa hoạn, với mặt nạ chống khói, chăn chữa cháy và bình xịt.",
        prod_multi_title: "Bộ kit đa tình huống",
        prod_multi_desc: "Giải pháp toàn diện nhất chuẩn bị cho mọi thảm họa bất ngờ như động đất hoặc mất điện diện rộng.",
        prod_individual_title: "Mua lẻ trang thiết bị",
        prod_individual_desc: "Tự thiết kế bộ kit cho riêng gia đình bạn với các món đồ lẻ chất lượng cao như đèn pin, kìm đa năng và túi y tế.",
        btn_details: "Xem chi tiết",
        btn_disabled: "Đang phát triển",
        badge_popular: "Phổ biến nhất",
        badge_coming_soon: "Sắp ra mắt",
        page_products_title: "Chi tiết sản phẩm",
        price_label: "Giá bán:",
        price_flood: "1.200.000 VNĐ",
        feat_flood_adv_1: "<strong>Giải pháp sinh tồn toàn diện:</strong> Tích hợp đầy đủ trang thiết bị thiết yếu từ phao cứu sinh, đèn pin năng lượng mặt trời đến bộ y tế chuyên dụng.",
        feat_flood_adv_2: "<strong>Thiết kế tối ưu cho môi trường ngập lụt:</strong> Balo và các phụ kiện chống thấm nước cao cấp, bền bỉ và dễ dàng mang theo.",
        feat_flood_adv_3: "<strong>Phản ứng nhanh và sẵn sàng tức thì:</strong> Vật dụng sắp xếp khoa học, gọn nhẹ, giúp bạn bảo vệ gia đình trong giây phút quan trọng nhất.",
        price_flood_old: "1.500.000 VNĐ",
        sale_ends_in: "Deal kết thúc sau:",
        time_days: "Ngày",
        price_multi: "2.500.000 VNĐ",
        feat_multi_1: "Balo chịu lực chống nước",
        feat_multi_2: "Dụng cụ lọc nước mini",
        feat_multi_3: "Bộ y tế cá nhân toàn diện",
        feat_multi_4: "Thức ăn dự trữ cao năng lượng",
        price_indi: "Từ 150.000 VNĐ",
        feat_indi_1: "Đèn pin chiến thuật siêu sáng (250K)",
        feat_indi_2: "Kìm đa năng 12 in 1 (300K)",
        feat_indi_3: "Túi y tế cơ bản cho gia đình (150K)",
        feat_indi_4: "Còi sinh tồn thông minh (50K)",
        why_title: "Vì sao chọn SAFEALL",
        why_1: "Bộ kit được thiết kế theo từng tình huống cụ thể",
        why_2: "Phù hợp với đặc thù hộ gia đình Việt Nam",
        why_3: "Hướng dẫn ứng phó khẩn cấp dễ hiểu, dễ làm",
        why_4: "Trang thiết bị an toàn, độ bền cao và đáng tin cậy",
        cta_title: "Chuẩn bị ngay hôm nay để bảo vệ gia đình bạn.",
        cta_btn: "Mua ngay",
        footer_slogan: "Chuẩn bị hôm nay – An toàn ngày mai.",
        footer_links_title: "Liên kết nhanh",
        footer_contact_title: "Liên hệ",
        footer_lang_title: "Ngôn ngữ",
        checkout_title: "Thông tin thanh toán",
        checkout_address: "Địa Chỉ Nhận Hàng",
        checkout_product: "Sản phẩm",
        checkout_unit_price: "Đơn giá",
        checkout_quantity: "Số lượng",
        checkout_item_total: "Thành tiền",
        checkout_note: "Lời nhắn:",
        checkout_note_placeholder: "Lưu ý cho Người bán...",
        checkout_shipping: "Đơn vị vận chuyển:",
        checkout_voucher: "SAFEALL Voucher",
        checkout_btn_order: "Đặt hàng",
        checkout_merchandise_subtotal: "Tổng tiền hàng",
        checkout_shipping_total: "Tổng tiền phí vận chuyển",
        checkout_total_payment: "Tổng thanh toán",
        checkout_invoice: "Hóa đơn điện tử",
        checkout_req_invoice: "Yêu Cầu Ngay",
        checkout_shop_voucher: "Voucher của Shop",
        checkout_choose_voucher: "Chọn Voucher",
        checkout_success_title: "Đặt hàng thành công!",
        checkout_success_msg: "Cảm ơn bạn đã mua sắm tại SAFEALL.",
        checkout_success_eta: "Dự kiến giao hàng: 2-3 ngày làm việc",
        checkout_success_home: "Về trang chủ",
        checkout_success_admin: "Xem Quản Lý Đơn",
        checkout_indi_1_name: "Đèn pin chiến thuật siêu sáng",
        checkout_indi_2_name: "Kìm đa năng 12 in 1",
        checkout_indi_3_name: "Túi y tế cơ bản cho gia đình",
        checkout_indi_4_name: "Còi sinh tồn thông minh",
        form_name: "Họ và tên",
        form_phone: "Số điện thoại",
        form_email: "Email",
        form_address: "Địa chỉ nhận hàng (Ví dụ: Số nhà, Đường, Phường/Xã, Quận/Huyện, Tỉnh/Thành phố)",
        form_note: "Ghi chú cho cửa hàng",
        order_summary: "Tóm tắt đơn hàng",
        discount_code: "Mã giảm giá",
        btn_apply: "Áp dụng",
        payment_method: "Phương thức thanh toán",
        pay_cod: "Thanh toán khi giao hàng (COD)",
        pay_bank: "Chuyển khoản ngân hàng",
        btn_confirm_order: "Xác nhận mua hàng",
        summary_subtotal: "Tạm tính",
        summary_shipping: "Phí giao hàng",
        summary_total: "Tổng cộng",
        order_success_msg: "Đơn hàng của bạn đã được xác nhận thành công! Chúng tôi sẽ liên hệ với bạn trong thời gian sớm nhất.",
        secure_checkout: "Thanh toán an toàn & bảo mật",
        processing: "Đang xử lý..."
    },
    en: {
        nav_about: "About",
        nav_mission: "Mission",
        nav_products: "Products",
        nav_reasons: "Why SAFEALL",
        hero_title: "Prepare Today –<br><span class=\"highlight\">Stay Safe Tomorrow</span>",
        hero_desc: "Protect your family in any emergency with essential preparedness kits from SAFEALL.",
        hero_cta: "Explore Kits",
        about_title: "About SAFEALL",
        about_desc: "SAFEALL is a brand providing emergency preparedness kits designed for households, helping families respond quickly and effectively to emergencies such as floods, fires, and unexpected disasters.",
        vision_title: "Vision",
        vision_desc: "Building a safe and proactive community of Vietnamese families in the face of emergencies.",
        mission_title: "Mission",
        mission_desc: "Providing easy-to-use, reliable emergency preparedness kits tailored to the needs of households.",
        goals_title: "Our Goals",
        goals_1: "Raise awareness about household emergency preparedness",
        goals_2: "Provide safe and reliable emergency kits",
        goals_3: "Build a proactive risk-prevention community",
        products_title: "Product Categories",
        products_subtitle: "Choose the right kit to protect your family.",
        prod_flood_title: "Flood Emergency Kit",
        prod_flood_desc: "Specially designed to protect families in flood situations, including waterproof items and life jackets.",
        prod_fire_title: "Fire Emergency Kit",
        prod_fire_desc: "Helps your family escape safely during a fire, equipped with smoke masks, fire blankets, and extinguishers.",
        prod_multi_title: "Multi-Hazard Emergency Kit",
        prod_multi_desc: "The most comprehensive solution to prepare for any unexpected disaster like earthquakes or wide-spread power outages.",
        prod_individual_title: "Individual Gear",
        prod_individual_desc: "Build your own kit with high-quality individual items like flashlights, multi-tools, and first aid kits.",
        btn_details: "View Details",
        btn_disabled: "In Development",
        badge_popular: "Most Popular",
        badge_coming_soon: "Coming Soon",
        page_products_title: "Product Details",
        price_label: "Price:",
        price_flood: "1,200,000 VND",
        feat_flood_adv_1: "<strong>Comprehensive Survival Solution:</strong> Fully integrated with essential gear from life jackets to solar flashlights and medical kits.",
        feat_flood_adv_2: "<strong>Optimized for Flood Environments:</strong> High-quality waterproof materials, durable and easy to carry through floodwaters.",
        feat_flood_adv_3: "<strong>Instant Readiness & Rapid Response:</strong> Scientifically organized and lightweight for quick action in critical moments.",
        price_flood_old: "1,500,000 VND",
        sale_ends_in: "Sale ends in:",
        time_days: "Days",
        price_multi: "2,500,000 VND",
        feat_multi_1: "Heavy-Duty Waterproof Backpack",
        feat_multi_2: "Mini Water Filter",
        feat_multi_3: "Comprehensive First Aid Kit",
        feat_multi_4: "High-Energy Food Rations",
        price_indi: "From 150,000 VND",
        feat_indi_1: "Bright Tactical Flashlight (250K)",
        feat_indi_2: "12-in-1 Multi-tool (300K)",
        feat_indi_3: "Basic Home First Aid Kit (150K)",
        feat_indi_4: "Smart Survival Whistle (50K)",
        why_title: "Why Choose SAFEALL",
        why_1: "Scenario-based emergency kits",
        why_2: "Designed for Vietnamese households",
        why_3: "Easy-to-follow emergency instructions",
        why_4: "Reliable, highly durable safety equipment",
        cta_title: "Start preparing today to protect your family.",
        cta_btn: "Shop Now",
        footer_slogan: "Prepare Today – Stay Safe Tomorrow.",
        footer_links_title: "Quick Links",
        footer_contact_title: "Contact",
        footer_lang_title: "Language",
        checkout_title: "Checkout",
        checkout_address: "Delivery Address",
        checkout_product: "Product",
        checkout_unit_price: "Unit Price",
        checkout_quantity: "Quantity",
        checkout_item_total: "Item Total",
        checkout_note: "Message:",
        checkout_note_placeholder: "Note for Seller...",
        checkout_shipping: "Shipping Method:",
        checkout_voucher: "SAFEALL Voucher",
        checkout_btn_order: "Place Order",
        checkout_merchandise_subtotal: "Merchandise Subtotal",
        checkout_shipping_total: "Shipping Total",
        checkout_total_payment: "Total Payment",
        checkout_invoice: "E-Invoice",
        checkout_req_invoice: "Request Now",
        checkout_shop_voucher: "Shop Voucher",
        checkout_choose_voucher: "Select Voucher",
        checkout_success_title: "Order Placed Successfully!",
        checkout_success_msg: "Thank you for shopping at SAFEALL.",
        checkout_success_eta: "Estimated Delivery: 2-3 business days",
        checkout_success_home: "Back to Home",
        checkout_success_admin: "View Orders",
        checkout_indi_1_name: "Bright Tactical Flashlight",
        checkout_indi_2_name: "12-in-1 Multi-tool",
        checkout_indi_3_name: "Basic Home First Aid Kit",
        checkout_indi_4_name: "Smart Survival Whistle",
        form_name: "Full Name",
        form_phone: "Phone Number",
        form_email: "Email",
        form_address: "Shipping Address (Apt, Street, Ward, District, City)",
        form_note: "Order Notes",
        order_summary: "Order Summary",
        discount_code: "Discount Code",
        btn_apply: "Apply",
        payment_method: "Payment Method",
        pay_cod: "Cash on Delivery (COD)",
        pay_bank: "Bank Transfer",
        btn_confirm_order: "Confirm Order",
        summary_subtotal: "Subtotal",
        summary_shipping: "Shipping Fee",
        summary_total: "Total",
        order_success_msg: "Your order has been successfully placed! We will contact you soon.",
        secure_checkout: "Secure & Encrypted Checkout",
        processing: "Processing..."
    }
};
